/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        /* ── MD3 Mavia tokens ── */
        primary:                  'var(--primary)',
        'on-primary':             'var(--on-primary)',
        'primary-container':      'var(--primary-container)',
        'on-primary-container':   'var(--on-primary-container)',
        'primary-fixed':          'var(--primary-fixed)',
        'primary-fixed-dim':      'var(--primary-fixed-dim)',
        secondary:                'var(--secondary)',
        'on-secondary':           'var(--on-secondary)',
        'secondary-container':    'var(--secondary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        tertiary:                 'var(--tertiary)',
        'on-tertiary':            'var(--on-tertiary)',
        'tertiary-container':     'var(--tertiary-container)',
        'on-tertiary-container':  'var(--on-tertiary-container)',
        error:                    'var(--error)',
        'on-error':               'var(--on-error)',
        'error-container':        'var(--error-container)',
        'on-error-container':     'var(--on-error-container)',
        background:               'var(--background)',
        'on-background':          'var(--on-background)',
        surface:                  'var(--surface)',
        'on-surface':             'var(--on-surface)',
        'surface-container':      'var(--surface-container)',
        'surface-container-low':  'var(--surface-container-low)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-container-lowest':  'var(--surface-container-lowest)',
        'surface-variant':        'var(--surface-variant)',
        'on-surface-variant':     'var(--on-surface-variant)',
        outline:                  'var(--outline)',
        'outline-variant':        'var(--outline-variant)',
        'inverse-surface':        'var(--inverse-surface)',
        'inverse-on-surface':     'var(--inverse-on-surface)',
        /* shadcn/ui semantic aliases */
        border:       'var(--outline-variant)',
        input:        'var(--outline-variant)',
        ring:         'var(--primary)',
        foreground:   'var(--on-surface)',
        muted:        'var(--surface-container)',
        'muted-foreground': 'var(--on-surface-variant)',
        accent:       'var(--primary-container)',
        'accent-foreground': 'var(--on-primary-container)',
        destructive:        'var(--error)',
        'destructive-foreground': 'var(--on-error)',
        card:         'var(--surface-container-lowest)',
        'card-foreground': 'var(--on-surface)',
        popover:      'var(--surface-container-lowest)',
        'popover-foreground': 'var(--on-surface)',
      },
      borderRadius: {
        lg:   '1rem',
        md:   '0.75rem',
        sm:   '0.5rem',
        xl:   '1.5rem',
        '2xl':'2rem',
        full: '9999px',
      },
      fontFamily: {
        sans:    ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        display: ['EB Garamond', 'Georgia', 'serif'],
      },
      boxShadow: {
        card: '0 4px 20px rgba(112,87,101,0.06)',
        fab:  '0 8px 32px rgba(112,87,101,0.35)',
        nav:  '0 -4px 24px rgba(0,0,0,0.06)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to:   { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to:   { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-in':        'fade-in 0.4s ease-out',
      },
    },
  },
  plugins: [],
};
